version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "3.12"
    commands: 
      - mkdir --parents $READTHEDOCS_OUTPUT/html
      - cp --recursive docs/transferchain/* $READTHEDOCS_OUTPUT/html
